<a href="https://colab.research.google.com/github/anshulpratap91/Digit_Recognition/blob/main/Image_Classification_CIFAR10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.datasets import cifar10

In [2]:
#load CIFAR10 data
(trainX, trainy), (testX, testy) = cifar10.load_data()

170508288/170498071 [==============================] - 6s 0us/step


In [3]:
#normalize datasets
trainx_norm=trainX/255
testx_norm=testX/255

In [4]:
#1st scenario : create ANN model using Keras
model=keras.Sequential([
                        keras.layers.Flatten(input_shape=(32,32,3)),
                        keras.layers.Dense(1000,activation='relu'),
                        keras.layers.Dense(500,activation='relu'),
                        keras.layers.Dense(10,activation='sigmoid')
])

In [5]:
#compile the model
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [6]:
#run the model for 15 epochs
model.fit(trainx_norm,trainy,epochs=15)

Epoch 1/15
1563/1563 [==============================] - 11s 5ms/step - loss: 1.8547 - accuracy: 0.3297
Epoch 2/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.6639 - accuracy: 0.4024
Epoch 3/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.5881 - accuracy: 0.4317
Epoch 4/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.5350 - accuracy: 0.4498
Epoch 5/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.5006 - accuracy: 0.4609
Epoch 6/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.4697 - accuracy: 0.4751
Epoch 7/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.4457 - accuracy: 0.4820
Epoch 8/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.4251 - accuracy: 0.4905
Epoch 9/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.4034 - accuracy: 0.4984
Epoch 10/15
1563/1563 [==============================] - 8s 5ms/step - loss: 1.38

In [7]:
#2nd scenario : create CNN model
cnn=keras.Sequential([
                     keras.layers.Conv2D(filters=64,kernel_size=(3,3),activation='relu',input_shape=(32,32,3)),
                     keras.layers.MaxPool2D(2,2),

                     keras.layers.Conv2D(filters=32,kernel_size=(3,3),activation='relu'),
                     keras.layers.MaxPool2D(2,2),

                     keras.layers.Flatten(),
                     keras.layers.Dense(1000,activation='relu'),
                     keras.layers.Dense(500,activation='relu'),
                     keras.layers.Dense(10,activation='sigmoid')                       
])

In [8]:
cnn.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [9]:
cnn.fit(trainx_norm,trainy,epochs=15)

Epoch 1/15
1563/1563 [==============================] - 39s 8ms/step - loss: 1.4632 - accuracy: 0.4678
Epoch 2/15
1563/1563 [==============================] - 11s 7ms/step - loss: 1.0934 - accuracy: 0.6131
Epoch 3/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.9065 - accuracy: 0.6822
Epoch 4/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.7557 - accuracy: 0.7326
Epoch 5/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.6241 - accuracy: 0.7786
Epoch 6/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.4946 - accuracy: 0.8235
Epoch 7/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.3795 - accuracy: 0.8640
Epoch 8/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.2918 - accuracy: 0.8956
Epoch 9/15
1563/1563 [==============================] - 11s 7ms/step - loss: 0.2206 - accuracy: 0.9210
Epoch 10/15
1563/1563 [==============================] - 11s 7ms/step - l

In [10]:
#3rd scenario : crate SVM model with custom parameters
from sklearn.svm import SVC
svc_model = SVC(C=1, kernel='linear', gamma="auto")

In [11]:
#reshape test and train input vectors and extract a sample of 10K entries
trainX_new_shape = np.reshape(trainx_norm, (trainx_norm.shape[0], -1))
testX_new_shape = np.reshape(testx_norm, (testx_norm.shape[0], -1))

trainy_new_shape= np.reshape(trainy,(50000,))

trainX_new_shape1 = trainX_new_shape[:10000,:]
testX_new_shape1 = testX_new_shape[:10000,:]

trainy_new_shape1 = trainy_new_shape[:10000]
testy_new_shape1 = testy[:10000]


In [12]:
svc_model.fit(trainX_new_shape1,trainy_new_shape1)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
y_predict=svc_model.predict(testX_new_shape1)

In [14]:
#load classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

print(confusion_matrix(testy_new_shape1,y_predict))
print(classification_report(testy_new_shape1,y_predict))

[[420  40 105  38  45  36  17  51 194  54]
 [ 84 380  63  75  43  47  30  48  94 136]
 [108  38 307 116 130  85  84  70  35  27]
 [ 62  66 134 260  93 144 113  59  35  34]
 [ 69  28 178 103 276  94 109  95  28  20]
 [ 76  42 147 183 130 219  84  56  44  19]
 [ 27  41 131 189 114  76 316  54  18  34]
 [ 66  53 101  93 134  98  43 328  33  51]
 [215  73  48  44  29  36  16  22 456  61]
 [113 207  50  68  40  26  35  78 101 282]]
              precision    recall  f1-score   support

           0       0.34      0.42      0.38      1000
           1       0.39      0.38      0.39      1000
           2       0.24      0.31      0.27      1000
           3       0.22      0.26      0.24      1000
           4       0.27      0.28      0.27      1000
           5       0.25      0.22      0.24      1000
           6       0.37      0.32      0.34      1000
           7       0.38      0.33      0.35      1000
           8       0.44      0.46      0.45      1000
           9       0.39     